name: quick_access
description: A extension for easy access for any theme values
version: 1.0.0
homepage: https://github.com/onatcipli/quick_access.git

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
